### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by livein21st** [wietsedv/bertje#23]
Hi, 

My name is Nirav, currently pursuing Ph.D. at TU Delft on NL and NE extraction from dutch historical text.

I found your model on huggingface and really wanted to try it out with my own experiment. However, I don't if this model can be used with Spacy and Apple M1 chip. 

Do you have any instructions to steps written specifically for using Bertje with spacy on the Apple M1 machine?
Also I was wondering if you have time to about the NLP pipeline in Spacy with Bertje model?

Let me know.

Thank you.

**Comment by wietsedv** [comment]
You can use BERTje perfectly fine on the Apple M1 chip since PyTorch has Apple Silicon support. I do not have experience with transformers via Spacy, but if you can use any HuggingFace model hub model via Spacy, it should work exactly the same as with original English BERT. I do not have the intention to invest any time into researching Spacy compatibility.

Good luck!

**Comment by livein21st** [comment]
Okay, Thanks for this information. I will try to setup a pipeline and use this model for some NE extraction.
